// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using financial_planner.Database;

#nullable disable

namespace financial_planner.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("financial_planner.Models.Expense", b =>
                {
                    b.Property<int>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpenseId"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ExpenseTypeId")
                        .HasColumnType("int");

                    b.Property<int>("FinanceId")
                        .HasColumnType("int");

                    b.HasKey("ExpenseId");

                    b.HasIndex("ExpenseTypeId");

                    b.HasIndex("FinanceId");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            ExpenseId = 1,
                            Amount = 300.0,
                            Description = "All the software",
                            ExpenseTypeId = 0,
                            FinanceId = 1
                        },
                        new
                        {
                            ExpenseId = 2,
                            Amount = 700.0,
                            Description = "New Staff",
                            ExpenseTypeId = 1,
                            FinanceId = 2
                        },
                        new
                        {
                            ExpenseId = 3,
                            Amount = 500.0,
                            Description = "All the other",
                            ExpenseTypeId = 2,
                            FinanceId = 3
                        });
                });

            modelBuilder.Entity("financial_planner.Models.ExpenseType", b =>
                {
                    b.Property<int>("ExpenseTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExpenseTypeId");

                    b.ToTable("ExpenseType");

                    b.HasData(
                        new
                        {
                            ExpenseTypeId = 0,
                            Type = "Software"
                        },
                        new
                        {
                            ExpenseTypeId = 1,
                            Type = "Staff"
                        },
                        new
                        {
                            ExpenseTypeId = 2,
                            Type = "Other"
                        });
                });

            modelBuilder.Entity("financial_planner.Models.Finance", b =>
                {
                    b.Property<int>("FinanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FinanceId"));

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("FinanceId");

                    b.ToTable("Finances");

                    b.HasData(
                        new
                        {
                            FinanceId = 1,
                            Month = "December",
                            Year = 2023
                        },
                        new
                        {
                            FinanceId = 2,
                            Month = "January",
                            Year = 2024
                        },
                        new
                        {
                            FinanceId = 3,
                            Month = "February",
                            Year = 2024
                        });
                });

            modelBuilder.Entity("financial_planner.Models.Revenue", b =>
                {
                    b.Property<int>("RevenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RevenueId"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FinanceId")
                        .HasColumnType("int");

                    b.HasKey("RevenueId");

                    b.HasIndex("FinanceId");

                    b.ToTable("Revenues");

                    b.HasData(
                        new
                        {
                            RevenueId = 1,
                            Amount = 1500.0,
                            Description = "Client A",
                            FinanceId = 1
                        },
                        new
                        {
                            RevenueId = 2,
                            Amount = 500.0,
                            Description = "Client B",
                            FinanceId = 1
                        },
                        new
                        {
                            RevenueId = 3,
                            Amount = 2000.0,
                            Description = "Client B",
                            FinanceId = 2
                        },
                        new
                        {
                            RevenueId = 4,
                            Amount = 2500.0,
                            Description = "Client A",
                            FinanceId = 3
                        });
                });

            modelBuilder.Entity("financial_planner.Models.Expense", b =>
                {
                    b.HasOne("financial_planner.Models.ExpenseType", "ExpenseType")
                        .WithMany("Expenses")
                        .HasForeignKey("ExpenseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("financial_planner.Models.Finance", "Finance")
                        .WithMany("Expenses")
                        .HasForeignKey("FinanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseType");

                    b.Navigation("Finance");
                });

            modelBuilder.Entity("financial_planner.Models.Revenue", b =>
                {
                    b.HasOne("financial_planner.Models.Finance", "Finance")
                        .WithMany("Revenues")
                        .HasForeignKey("FinanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Finance");
                });

            modelBuilder.Entity("financial_planner.Models.ExpenseType", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("financial_planner.Models.Finance", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Revenues");
                });
#pragma warning restore 612, 618
        }
    }
}
